import { PARAM_TYPE } from "./fx-param-common";

const cab = [
    { id: 0, label: 'Cab L', type: PARAM_TYPE.Select, labelGroup: 'Basic' },
    { id: 1, label: 'Cab L mic', type: PARAM_TYPE.Select },
    { id: 2, label: 'Cab R', type: PARAM_TYPE.Select },
    { id: 3, label: 'Cab R mic', type: PARAM_TYPE.Select },
    { id: 4, label: 'Link cabs', type: PARAM_TYPE.Switch },
    { id: 5, label: 'Level L', type: PARAM_TYPE.Knob },
    { id: 6, label: 'Level R', type: PARAM_TYPE.Knob },
    { id: 7, label: 'Pan L', type: PARAM_TYPE.Knob, range: [-100, 100], precision: 0 },
    { id: 8, label: 'Pan R', type: PARAM_TYPE.Knob, range: [-100, 100], precision: 0 },
    { id: 9, label: 'Level', type: PARAM_TYPE.Knob, range: [-80, 20] },
    { id: 10, label: 'Balance', type: PARAM_TYPE.Knob, range: [-100, 100], precision: 0 },
    { id: 11, label: 'Link cabs', type: PARAM_TYPE.Select },
    { id: 12, label: 'Link cabs', type: PARAM_TYPE.Select },
    { id: 14, label: 'Link cabs', type: PARAM_TYPE.Knob },
    { id: 15, label: 'Link cabs', type: PARAM_TYPE.Knob },
    { id: 16, label: 'Link cabs', type: PARAM_TYPE.Knob },
    { id: 17, label: 'Link cabs', type: PARAM_TYPE.Knob },
    { id: 18, label: 'Link cabs', type: PARAM_TYPE.Knob },
    { id: 19, label: 'Low cut', type: PARAM_TYPE.Knob },
    { id: 20, label: 'High cut', type: PARAM_TYPE.Knob },
    { id: 21, label: 'Speaker size', type: PARAM_TYPE.Knob },
    { id: 22, label: 'Proximity', type: PARAM_TYPE.Knob },
    { id: 23, label: 'Air', type: PARAM_TYPE.Knob },
    { id: 24, label: 'Motor drive', type: PARAM_TYPE.Knob },
    { id: 25, label: 'Air freq', type: PARAM_TYPE.Knob },
    { id: 26, label: 'Delay L', type: PARAM_TYPE.Knob },
    { id: 27, label: 'Delay R', type: PARAM_TYPE.Knob },
    { id: 28, label: 'Promixity R', type: PARAM_TYPE.Knob },
    { id: 29, label: 'Proximity freq', type: PARAM_TYPE.Knob },
    { id: 30, label: 'Input select', type: PARAM_TYPE.Select },
    { id: 31, label: 'Premap type', type: PARAM_TYPE.Select },
    { id: 32, label: 'Bass', type: PARAM_TYPE.Knob },
    { id: 33, label: 'Middle', type: PARAM_TYPE.Knob },
    { id: 34, label: 'Treble', type: PARAM_TYPE.Knob },
    { id: 35, label: 'Preamp mode', type: PARAM_TYPE.Select },
    { id: 36, label: 'Dephase', type: PARAM_TYPE.Knob },
    { id: 37, label: 'Filter slope', type: PARAM_TYPE.Select },
    { id: 38, label: 'Motor time constant', type: PARAM_TYPE.Knob }
];

export default cab;