export const ampType = [
    '59 Bassguy',
    '65 Bassguy Nrml',
    'Vibrato Verb',
    'Deluxe Verb Vib',
    'Double Verb Vib',
    'Jr Blues',
    'Class-A 15W TB',
    'Class-A 30W',
    'Class-A 30W TB',
    'Brit JM45',
    'Plexi 50W Nrml',
    'Plexi 50W Hi 1',
    '1987X Normal',
    '1987X Treble',
    'Brit 800',
    'Brit Super',
    'Hipower Normal',
    'Hipower Brillnt',
    'USA Clean',
    'USA Pre Clean',
    'USA Rhythm',
    'USA IIC+',
    'USA IIC+ Bright',
    'USA Lead',
    'USA Lead Brt',
    'Recto2 Org Vntg',
    'Recto2 Org Mdrn',
    'Recto2 Red Vntg',
    'Recto2 Red Mdrn',
    'Euro Blue',
    'Euro Red',
    'Shiver Clean',
    'Shiver Lead',
    'Euro Uber',
    'Solo 99 Clean',
    'Solo 100 Rhy',
    'Solo 100 Lead',
    'Friedman BE V1',
    'Friedman HBE V1',
    'PVH 6160 Block',
    'Mr Z Mz-38',
    'CA3+ Rhy',
    'CA3+ Lead',
    'Wrecker Rocket',
    'Corncob M50',
    'CA OD 2',
    'Fryette D60 L',
    'Fryette D60 M',
    'Brit Brown',
    'Citrus Rv50',
    'Jazz 120',
    'Energyball',
    'ODS-100 Clean',
    'ODS-100 HRM',
    'FAS Rhythm',
    'FAS Lead 1',
    'FAS Lead 2',
    'FAS Modern',
    'Das Metall',
    'Brit Pre',
    'Buttery',
    'Boutique 1',
    'Boutique 2',
    'Cameron CCV 1A',
    'Cameron CCV 2A',
    'SV Bass',
    'Tube Pre',
    'FAS Brown',
    'Big Hair',
    'Solo 99 Lead',
    'Supertweed',
    'TX Star Lead',
    'FAS Wreck',
    'Brit JVM OD1 Or',
    'Brit JVM OD2 Or',
    'FAS 6160',
    'Cali Leggy',
    'USA Lead',
    'USA Lead Brt',
    'Prince Tone',
    'Blankenship Leeds',
    '5153 100W Green',
    '5153 100W Blue',
    '5153 100W Red',
    'Solo 88 Rhythm',
    'Div/13 CJ',
    'Herbie Ch2',
    'Herbie Ch2',
    'Herbie Ch3',
    'Dirty Shirley 1',
    'Dizzy V4 Blue 2',
    'Dizzy V4 Blue 3',
    'Dizzy V4 Blue 4',
    'Suhr Badger 18',
    'Suhr Badger 30',
    'Prince Tone NR',
    'Supremo Trem',
    'Atomica Low',
    'Atomica High',
    'Deluxe Tweed',
    'Spawn Rod OD2 1',
    'Spawn Rod OD2 2',
    'Spawn Rod OD2 3',
    'Brit Silver',
    'Spawn Nitrous 2',
    'FAS Crunch',
    'Two Stone J35 1',
    'Fox ODS',
    'Hot Kitty',
    'Band Commander',
    'Super Verb Vib',
    'Vibra-King',
    'Gibtone Scout',
    'PVH 6160 LD',
    'Solo 100 Clean',
    'USA Pre LD2 Grn',
    'USA Pre LD2 Ylw',
    'CA3 Clean',
    'Fox ODS Deep',
    'Brit JVM OD1 Gn',
    'Brit JVM OD2 Gn',
    'Vibrato-Lux',
    'Brit 800 Mod',
    'Nuclear Tone',
    'Bludojai Clean',
    'Bludojai LD Pab',
    'Plexi 100W High',
    'Plexi 100W Nrml',
    'Ruby Rocket',
    'AC-20 EF86 B',
    'Prince Tone Rev',
    'Comet Concourse',
    'FAS Modern II',
    'CA Triptik Mdrn',
    'CA Triptik Clsc',
    'CA Triptik Cln',
    'Thordendal Vint',
    'Thordendal Mdrn',
    'ODS-100 HRM Mid',
    'Euro Blue Mdrn',
    'Euro Red Mdrn',
    'Plexi 50W Jump',
    'AC-20 EF86 T',
    'Comet 60',
    'Hipower Jumped',
    'Plexi 100W Jump',
    'Brit JM45 Jump',
    '1987X Jump',
    'Recto1 Org Vntg',
    'Recto1 Red',
    'ODS-100 Ford 1',
    'Bogfish Strato',
    'Bogfish Brown',
    '5F1 Tweed',
    'Wrecker Express',
    'Two Stone J35 2',
    'ODS-100 Ford 2',
    'Mr Z Mz-8',
    'Car Roamer',
    'USA Sub Blues',
    'Wrecker Liverpool',
    'Citrus Terrier',
    'Citrus A30 Cln',
    'Citrus A30 Drty',
    'Div/13 FT37 Lo',
    'Div/13 FT37 Hi',
    'Matchbox D-30',
    'FAS Class-A',
    'USA Bass 400 1',
    'USA Bass 400 2',
    'Citrus Bass 200',
    'FAS Bass',
    'Tremolo Lux',
    'FAS Brootalz',
    'Recto1 Org Mdrn',
    'Angle Severe 1',
    'Angle Severe 2',
    'UAS Pre Ld2 Red',
    'UAS Pre Ld1 Red',
    'TX Star Clean',
    'AC-20 12AX7 T',
    'Vibrato Verb AA',
    'Vibrato Verb AB',
    'CA Tucana Lead',
    'Jr Blues Fat',
    'Solo 88 Lead',
    'Brit AFS100 1',
    'Brit AFS100 2',
    'Class-A 30W Hot',
    'Dizzy V4 Slvr 2',
    'Dizzy V4 Slvr 3',
    'Dizzy V4 Slvr 4',
    '1959 SLP Normal',
    '1959 SLP Treble',
    '1959 SLP Jump',
    'FAS Modern III',
    'ODS-100 Ford Md',
    'Mr Z Hwy 66',
    '6G4 Super',
    '6G12 Concert',
    '65 Bassguy Bass',
    'Vibra-King Fat',
    'Spawn Rod OD1 1',
    'Spawn Rod OD1 2',
    'Spawn Rod OD1 3',
    'CA Tucana Cln',
    'Brit JVM OD1 Rd',
    'Brit JVM OD2 Rd',
    'Cameron CCV 1B',
    'Cameron CCV 2B',
    'Cameron CCV 2C',
    'Cameron CCV 2D',
    'Friedman Sm Box',
    '5153 50W Blue',
    'Div/13 CJ Boost',
    'USA IIC+ Deep',
    'USA IIC+ Brt Dp',
    '5F8 Tweed',
    'Double Verb SF',
    'Vibrato Verb CS',
    'JMPre 1 Od1',
    'JMPre 1 Od2',
    'JMPre 1 Od1 Bs',
    'JMPre 1 Od2 Bs',
    'Deluxe Verb Nrm',
    'Double Verb Nrm',
    'Super Verb Nrm',
    'Bludojai LD 2',
    'Plexi 50W 6550',
    'FAS Hot Rod',
    'Pvh 6160 Rhy B',
    'Pvh 6160 Rhy',
    'Solo 88 Clean',
    'Class-A 30W Brt',
    'Plexi 50W Hi 2',
    'Spawn Nitrous 1',
    'Ruby Rocket Brt',
    'AC-20 12AX7 B',
    'Plexi 100W 1970',
    'JS410 Lead Or',
    'JS410 Lead Rd',
    'JS410 Crunch Or',
    'JS410 Crunch Rd',
    'Friedman BE V2',
    'Friedman HBE V2',
    'Dweezil\'s B-Man',
    'Friedman BE',
    'Friedman HBE',
    'USA IIC++',
    'Legato 100',
    'Capt Hook 2B',
    'Capt Hook 3B',
    'Capt Hook 2A',
    'Capt Hook 3A',
    'Capt Hook 1A',
    'Capt Hook 1B',
    'Dirty Shirley 2',
    'Brit 800 #34',
    '5F1 Tweed EC'
];

export const driveType = [
    'RAT DIST',
    'PI FUZZ',
    'TUBE DRV 3-KNOB',
    'SUPER OD',
    'TREBLE BOOST',
    'MID BOOST',
    'T808 OD',
    'FAT RAT',
    'T808 MOD',
    'OCTAVE DIST',
    'PLUS DIST',
    'HARD FUZZ',
    'FET BOOST',
    'TAPE DIST',
    'FULL OD',
    'BLUES OD',
    'SHRED DIST',
    'M-ZONE DIST',
    'BENDER FUZZ',
    'BB PRE',
    'MASTER FUZZ',
    'FACE FUZZ',
    'BIT CRUSHER',
    'ETERNAL LOVE',
    'ESOTERIC ACB',
    'ESOTERIC RCB',
    'ZEN MASTER',
    'TUBE DRV 4-KNOB',
    'FAS LED-DRIVE',
    'SDD PREAMP',
    'FET PREAMP',
    'RUCKUS',
    'MICRO BOOST',
    'FAS BOOST',
    'TIMOTHY',
    'SHIMMER DRIVE'
];

export const clipType = [
    'LV TUBE',
    'HARD',
    'SOFT',
    'GERMANIUM',
    'FW RECT',
    'HV TUBE',
    'SILICON',
    '4558/DIODE',
    'LED',
    'FET',
    'OP-AMP',
    'VARIABLE',
    'NULL'
];

export const delayType = [
    'DIGITAL MONO',
    'DIGITAL STEREO',
    'ANALOG MONO',
    'ANALOG STEREO',
    'MONO TAPE',
    'STEREO TAPE',
    'PING-PONG',
    'DUAL DELAY',
    'REVERSE DELAY',
    'SWEEP DELAY',
    'DUCKING DELAY',
    'VINTAGE DIGITAL',
    '2290 W/ MOD',
    'AMBIENT STEREO',
    'DELUXE MIND GUY',
    'MONO BBD',
    'STEREO BBD',
    'LO-FI TAPE'
];

export const delayConfig = [
    'MONO',
    'STEREO',
    'PING-PONG',
    'DUAL',
    'REVERSE',
    'SWEEP',
    'TAPE'
];

export const reverbType = [
    'SMALL ROOM',
    'MEDIUM ROOM',
    'LARGE ROOM',
    'SMALL HALL',
    'MEDIUM HALL',
    'LARGE HALL',
    'SMALL CHAMBER',
    'MEDIUM CHAMBER',
    'LARGE CHAMBER',
    'SMALL PLATE',
    'MEDIUM PLATE',
    'LARGE PLATE',
    'SMALL CATHEDRAL',
    'MED. CATHEDRAL',
    'LARGE CATHEDRAL',
    'SMALL SPRING',
    'MEDIUM SPRING',
    'LARGE SPRING',
    'CAVERN',
    'STONE QUARRY',
    'STUDIO',
    'AMBIENCE',
    'CONCERT HALL',
    'LARGE DEEP HALL',
    'REC STUDIO C',
    'NORTH CHURCH',
    'SOUTH CHURCH',
    'LONDON PLATE',
    'SUN PLATE',
    'HUGE ROOM',
    'DRUM ROOM',
    'HALLWAY',
    'TUNNEL',
    'DEEP CHAMBER',
    'LG WOODEN ROOM',
    'GYMNASIUM',
    'ASYLUM HALL',
    'DEEP SPACE',
    'REC STUDIO A',
    'LG TILED ROOM',
    'VOCAL PLATE',
    'WIDE HALL',
    'RICH HALL'
];

export const bypassModeLimited = [
    'THRU',
    'MUTE'
];

export const bypassMode = [
    'THRU',
    'MUTE FX OUT',
    'MUTE OUT',
    'MUTE FX IN',
    'MUTE IN"'
];

export const inputSelect = [
    'L+R',
    'Left',
    'Right'
];

export const lfoType = [
    'SINE',
    'TRIANGLE',
    'SQUARE',
    'SAW UP',
    'SAW DOWN',
    'RANDOM',
    'LOG',
    'EXP',
    'TRAPEZOID'
];

export const lfoTarget = [
    'Both',
    'Left',
    'Right'
];

export const lfoDepthRange = [
    'LOW',
    'HIGH',
];

export const phaseReverse = [
    'None',
    'Right',
    'Left',
    'Both',
];

export const filterSlope = [
    '6 dB/OCT',
    '12 dB/OCT',
    '24 dB/OCT',
    '36 dB/OCT',
    '48 dB/OCT'
];

export const tempo = [
    'NONE',
    '1/64 TRIP',
    '1/64',
    '1/64 DOT',
    '1/32 TRIP',
    '1/32',
    '1/32 DOT',
    '1/16 TRIP',
    '1/16',
    '1/16 DOT',
    '1/8 TRIP',
    '1/8',
    '1/8 DOT',
    '1/4 TRIP',
    '1/4',
    '1/4 DOT',
    '1/2 TRIP',
    '1/2',
    '1/2 DOT',
    '1 TRIP',
    '1',
    '1 DOT',
    '2',
    '3',
    '4',
    '4/3',
    '5/4',
    '5/64',
    '7/64',
    '9/64',
    '10/64 (5/32)',
    '11/64',
    '13/64',
    '14/64 (7/32)',
    '15/64',
    '17/64',
    '18/64 (9/32)',
    '19/64',
    '20/64 (5/16)',
    '21/64',
    '22/64 (11/32)',
    '23/64',
    '25/64',
    '26/64 (13/32)',
    '27/64',
    '28/64 (7/16)',
    '29/64',
    '30/64 (15/32)',
    '31/64',
    '33/64',
    '34/64 (17/32)',
    '35/64',
    '36/64 (9/16)',
    '37/64',
    '38/64 (19/32)',
    '39/64',
    '40/64 (5/8)',
    '41/64',
    '42/64 (21/32)',
    '43/64',
    '44/64 (11/16)',
    '45/64',
    '46/64 (23/32)',
    '47/64',
    '49/64',
    '50/64 (25/32)',
    '51/64',
    '52/64 (13/16)',
    '53/64',
    '54/64 (27/32)',
    '55/64',
    '56/64 (7/8)',
    '57/64',
    '58/64 (29/32)',
    '59/64',
    '60/64 (15/16)',
    '61/64',
    '62/64 (31/32)',
    '63/64',
];

const FX_PARAM_SELECT_VALUES = {
    ampType,
    delayType,
    delayConfig,
    clipType,
    driveType,
    bypassMode,
    bypassModeLimited,
    inputSelect,
    filterSlope,
    phaseReverse,
    lfoDepthRange,
    lfoTarget,
    lfoType
};

export default FX_PARAM_SELECT_VALUES;

