import { PARAM_TYPE } from "./fx-param-common";
import { bypassMode } from "./fx-param-select";

export const reverbType = [
    'SMALL ROOM',
    'MEDIUM ROOM',
    'LARGE ROOM',
    'SMALL HALL',
    'MEDIUM HALL',
    'LARGE HALL',
    'SMALL CHAMBER',
    'MEDIUM CHAMBER',
    'LARGE CHAMBER',
    'SMALL PLATE',
    'MEDIUM PLATE',
    'LARGE PLATE',
    'SMALL CATHEDRAL',
    'MED. CATHEDRAL',
    'LARGE CATHEDRAL',
    'SMALL SPRING',
    'MEDIUM SPRING',
    'LARGE SPRING',
    'CAVERN',
    'STONE QUARRY',
    'STUDIO',
    'AMBIENCE',
    'CONCERT HALL',
    'LARGE DEEP HALL',
    'REC STUDIO C',
    'NORTH CHURCH',
    'SOUTH CHURCH',
    'LONDON PLATE',
    'SUN PLATE',
    'HUGE ROOM',
    'DRUM ROOM',
    'HALLWAY',
    'TUNNEL',
    'DEEP CHAMBER',
    'LG WOODEN ROOM',
    'GYMNASIUM',
    'ASYLUM HALL',
    'DEEP SPACE',
    'REC STUDIO A',
    'LG TILED ROOM',
    'VOCAL PLATE',
    'WIDE HALL',
    'RICH HALL'
];

const reverb = [
    { id: 0, label: 'Type', type: PARAM_TYPE.Select, values: reverbType, step: 1, range: [0, reverbType.length - 1], labelGroup: 'Basic' },
    { id: 1, label: 'Time', type: PARAM_TYPE.Knob, step: 0.01, range: [0, 100], unit: 's' },
    { id: 2, label: 'High cut', type: PARAM_TYPE.Knob, range: [200, 20000], unit: 'Hz' },
    { id: 3, label: 'HF time', type: PARAM_TYPE.Knob, range: [0.1, 1], step: 0.01, precision: 0.01 },
    { id: 4, label: 'Wall diffusion', type: PARAM_TYPE.Knob },
    { id: 5, label: 'Size', type: PARAM_TYPE.Knob, range: [1, 100], step: 1 },
    { id: 7, label: 'Early level', type: PARAM_TYPE.Knob, range: [-40, 10], step: 1, unit: 'dB' },
    { id: 8, label: 'Late level', type: PARAM_TYPE.Knob, range: [-40, 10], step: 1, unit: 'dB' },
    { id: 9, label: 'Predelay', type: PARAM_TYPE.Knob, range: [0, 250], step: 1, unit: 'ms' },
    { id: 14, label: 'Level', type: PARAM_TYPE.Knob, range: [-80, 20], step: 1, precision: 1, unit: 'dB' },
    { id: 15, label: 'Balance', type: PARAM_TYPE.Knob },
    { id: 10, label: 'Low cut', type: PARAM_TYPE.Knob, range: [20, 2000], step: 1, unit: 'Hz' },
    { id: 11, label: 'Mod depth', type: PARAM_TYPE.Knob, labelGroup: 'Advanced' },
    { id: 12, label: 'Mod rate', type: PARAM_TYPE.Knob },
    { id: 13, label: 'Mix', type: PARAM_TYPE.Knob, range: [0, 100], unit: '%' },
    { id: 16, label: 'Bypass mode', type: PARAM_TYPE.Select, values: bypassMode },
    { id: 17, label: 'Global', type: PARAM_TYPE.Switch },
    { id: 18, label: 'Input gain', type: PARAM_TYPE.Knob },
    { id: 19, label: 'Echo density', type: PARAM_TYPE.Knob, range: [2, 8], step: 1, precision: 1 },
    { id: 20, label: 'Late diffusion', type: PARAM_TYPE.Knob },
    { id: 21, label: 'Late diff time', type: PARAM_TYPE.Knob },
    { id: 23, label: 'Spring number', type: PARAM_TYPE.Knob, range: [2, 6], step: 1, precision: 1 },
    { id: 24, label: 'Spring tone', type: PARAM_TYPE.Knob },
    { id: 25, label: 'Mic spacing', type: PARAM_TYPE.Knob },
    { id: 26, label: 'Freq 1', type: PARAM_TYPE.Knob },
    { id: 27, label: 'Freq 2', type: PARAM_TYPE.Knob },
    { id: 28, label: 'Q 1', type: PARAM_TYPE.Knob },
    { id: 29, label: 'Q 2', type: PARAM_TYPE.Knob },
    { id: 30, label: 'Gain 1', type: PARAM_TYPE.Knob },
    { id: 31, label: 'Gain 2', type: PARAM_TYPE.Knob },
    { id: 32, label: 'Spring drive', type: PARAM_TYPE.Knob },
    { id: 33, label: 'LF time', type: PARAM_TYPE.Knob, range: [0.5, 2], step: 0.01, precision: 0.01 },
    { id: 34, label: 'LF crossover', type: PARAM_TYPE.Knob, range: [100, 10000], step: 1, unit: 'Hz' },
    { id: 35, label: 'Stereo Width', type: PARAM_TYPE.Knob },
    { id: 36, label: 'Attenuation', type: PARAM_TYPE.Knob },
    { id: 37, label: 'Threshold', type: PARAM_TYPE.Knob },
    { id: 38, label: 'Release time', type: PARAM_TYPE.Knob },
    { id: 39, label: 'Early diffusion', type: PARAM_TYPE.Knob },
    { id: 40, label: 'Early diff time', type: PARAM_TYPE.Knob },
    { id: 41, label: 'Early decay', type: PARAM_TYPE.Knob },
    { id: 43, label: 'Quality', type: PARAM_TYPE.Select },
    { id: 44, label: 'Hold', type: PARAM_TYPE.Switch },
];

export default reverb;