export enum PARAM_TYPE {
    Select = 'select',
    Switch = 'switch',
    Knob = 'knob'
}

export const FX_PARAM_SELECT_VALUES = {
    ampType: [
        '59 BASSGUY',
        '65 BASSGUY NRML',
        'VIBRATO VERB',
        'DELUXE VERB VIB',
        'DOUBLE VERB VIB',
        'JR BLUES',
        'CLASS-A 15W TB',
        'CLASS-A 30W',
        'CLASS-A 30W TB',
        'BRIT JM45',
        'PLEXI 50W NRML',
        'PLEXI 50W HI 1',
        '1987X NORMAL',
        '1987X TREBLE',
        'BRIT 800',
        'BRIT SUPER',
        'HIPOWER NORMAL',
        'HIPOWER BRILLNT',
        'USA CLEAN',
        'USA PRE CLEAN',
        'USA RHYTHM',
        'USA IIC+',
        'USA IIC+ BRIGHT',
        'USA LEAD',
        'USA LEAD BRT',
        'RECTO2 ORG VNTG',
        'RECTO2 ORG MDRN',
        'RECTO2 RED VNTG',
        'RECTO2 RED MDRN',
        'EURO BLUE',
        'EURO RED',
        'SHIVER CLEAN',
        'SHIVER LEAD',
        'EURO UBER',
        'SOLO 99 CLEAN',
        'SOLO 100 RHY',
        'SOLO 100 LEAD',
        'FRIEDMAN BE V1',
        'FRIEDMAN HBE V1',
        'PVH 6160 BLOCK',
        'MR Z MZ-38',
        'CA3+ RHY',
        'CA3+ LEAD',
        'WRECKER ROCKET',
        'CORNCOB M50',
        'CA OD-2',
        'FRYETTE D60 L',
        'FRYETTE D60 M',
        'BRIT BROWN',
        'CITRUS RV50',
        'JAZZ 120',
        'ENERGYBALL',
        'ODS-100 CLEAN',
        'ODS-100 HRM',
        'FAS RHYTHM',
        'FAS LEAD 1',
        'FAS LEAD 2',
        'FAS MODERN',
        'DAS METALL',
        'BRIT PRE',
        'BUTTERY',
        'BOUTIQUE 1',
        'BOUTIQUE 2',
        'CAMERON CCV 1A',
        'CAMERON CCV 2A',
        'SV BASS',
        'TUBE PRE',
        'FAS BROWN',
        'BIG HAIR',
        'SOLO 99 LEAD',
        'SUPERTWEED',
        'TX STAR LEAD',
        'FAS WRECK',
        'BRIT JVM OD1 OR',
        'BRIT JVM OD2 OR',
        'FAS 6160',
        'CALI LEGGY',
        'USA LEAD +',
        'USA LEAD BRT +',
        'PRINCE TONE',
        'BLANKNSHP LEEDS',
        '5153 100W GREEN',
        '5153 100W BLUE',
        '5153 100W RED',
        'SOLO 88 RHYTHM',
        'DIV/13 CJ',
        'HERBIE CH2-',
        'HERBIE CH2+',
        'HERBIE CH3',
        'DIRTY SHIRLEY 1',
        'DIZZY V4 BLUE 2',
        'DIZZY V4 BLUE 3',
        'DIZZY V4 BLUE 4',
        'SUHR BADGER 18',
        'SUHR BADGER 30',
        'PRINCE TONE NR',
        'SUPREMO TREM',
        'ATOMICA LOW',
        'ATOMICA HIGH',
        'DELUXE TWEED',
        'SPAWN ROD OD2-1',
        'SPAWN ROD OD2-2',
        'SPAWN ROD OD2-3',
        'BRIT SILVER',
        'SPAWN NITROUS 2',
        'FAS CRUNCH',
        'TWO STONE J35 1',
        'FOX ODS',
        'HOT KITTY',
        'BAND-COMMANDER',
        'SUPER VERB VIB',
        'VIBRA-KING',
        'GIBTONE SCOUT',
        'PVH 6160+ LD',
        'SOLO 100 CLEAN',
        'USA PRE LD2 GRN',
        'USA PRE LD2 YLW',
        'CA3+ CLEAN',
        'FOX ODS DEEP',
        'BRIT JVM OD1 GN',
        'BRIT JVM OD2 GN',
        'VIBRATO LUX',
        'BRIT 800 MOD',
        'NUCLEAR-TONE',
        'BLUDOJAI CLEAN',
        'BLUDOJAI LD PAB',
        'PLEXI 100W HIGH',
        'PLEXI 100W NRML',
        'RUBY ROCKET',
        'AC-20 EF86 B',
        'PRINCE TONE REV',
        'COMET CONCOURSE',
        'FAS MODERN II',
        'CA TRIPTIK MDRN',
        'CA TRIPTIK CLSC',
        'CA TRIPTIK CLN',
        'THORDENDAL VINT',
        'THORDENDAL MDRN',
        'ODS-100 HRM MID',
        'EURO BLUE MDRN',
        'EURO RED MDRN',
        'PLEXI 50W JUMP',
        'AC-20 EF86 T',
        'COMET 60',
        'HIPOWER JUMPED',
        'PLEXI 100W JUMP',
        'BRIT JM45 JUMP',
        '1987X JUMP',
        'RECTO1 ORG VNTG',
        'RECTO1 RED',
        'ODS-100 FORD 1',
        'BOGFISH STRATO',
        'BOGFISH BROWN',
        '5F1 TWEED',
        'WRECKER EXPRESS',
        'TWO STONE J35 2',
        'ODS-100 FORD 2',
        'MR Z MZ-8',
        'CAR ROAMER',
        'USA SUB BLUES',
        'WRECKER LVRPOOL',
        'CITRUS TERRIER',
        'CITRUS A30 CLN',
        'CITRUS A30 DRTY',
        'DIV/13 FT37 LO',
        'DIV/13 FT37 HI',
        'MATCHBOX D-30',
        'FAS CLASS-A',
        'USA BASS 400 1',
        'USA BASS 400 2',
        'CITRUS BASS 200',
        'FAS BASS',
        'TREMOLO LUX',
        'FAS BROOTALZ',
        'RECTO1 ORG MDRN',
        'ANGLE SEVERE 1',
        'ANGLE SEVERE 2',
        'USA PRE LD2 RED',
        'USA PRE LD1 RED',
        'TX STAR CLEAN',
        'AC-20 12AX7 T',
        'VIBRATO VERB AA',
        'VIBRATO VERB AB',
        'CA TUCANA LEAD',
        'JR BLUES FAT',
        'SOLO 88 LEAD',
        'BRIT AFS100 1',
        'BRIT AFS100 2',
        'CLASS-A 30W HOT',
        'DIZZY V4 SLVR 2',
        'DIZZY V4 SLVR 3',
        'DIZZY V4 SLVR 4',
        '1959SLP NORMAL',
        '1959SLP TREBLE',
        '1959SLP JUMP',
        'FAS MODERN III',
        'ODS-100 FORD MD',
        'MR Z HWY 66',
        '6G4 SUPER',
        '6G12 CONCERT',
        '65 BASSGUY BASS',
        'VIBRA-KING FAT',
        'SPAWN ROD OD1-1',
        'SPAWN ROD OD1-2',
        'SPAWN ROD OD1-3',
        'CA TUCANA CLN',
        'BRIT JVM OD1 RD',
        'BRIT JVM OD2 RD',
        'CAMERON CCV 1B',
        'CAMERON CCV 2B',
        'CAMERON CCV 2C',
        'CAMERON CCV 2D',
        'FRIEDMAN SM BOX',
        '5153 50W BLUE',
        'DIV/13 CJ BOOST',
        'USA IIC+ DEEP',
        'USA IIC+ BRT/DP',
        '5F8 TWEED',
        'DOUBLE VERB SF',
        'VIBRATO VERB CS',
        'JMPRE-1 OD1',
        'JMPRE-1 OD2',
        'JMPRE-1 OD1 BS',
        'JMPRE-1 OD2 BS',
        'DELUXE VERB NRM',
        'DOUBLE VERB NRM',
        'SUPER VERB NRM',
        'BLUDOJAI LD 2',
        'PLEXI 50W 6550',
        'FAS HOT ROD',
        'PVH 6160+ RHY B',
        'PVH 6160+ RHY',
        'SOLO 88 CLEAN',
        'CLASS-A 30W BRT',
        'PLEXI 50W HI 2',
        'SPAWN NITROUS 1',
        'RUBY ROCKET BRT',
        'AC-20 12AX7 B',
        'PLEXI 100W 1970',
        'JS410 LEAD OR',
        'JS410 LEAD RD',
        'JS410 CRUNCH OR',
        'JS410 CRUNCH RD',
        'FRIEDMAN BE V2',
        'FRIEDMAN HBE V2',
        'DWEEZIL\'S B-MAN',
        'FRIEDMAN BE',
        'FRIEDMAN HBE',
        'USA IIC++',
        'LEGATO 100',
        'CAPT HOOK 2B',
        'CAPT HOOK 3B',
        'CAPT HOOK 2A',
        'CAPT HOOK 3A',
        'CAPT HOOK 1A',
        'CAPT HOOK 1B',
        'DIRTY SHIRLEY 2',
        'BRIT 800 #34',
        '5F1 TWEED EC'
    ]
};

export const FX_BLOCK_IDS = {
    amp1: 106,
    amp2: 107,
    cab1: 108,
    cab2: 109,
    chorus1: 116,
    chorus2: 117,
    compressor1: 100,
    compressor2: 101,
    multibandCompressor1: 154,
    multibandCompressor2: 155,
    crossover1: 148,
    crossover2: 149,
    delay1: 112,
    delay2: 113,
    multiDelay1: 114,
    multiDelay2: 115,
    megatapDelay: 147,
    drive1: 133,
    drive2: 134,
    enhancer: 135,
    fxLoop: 136,
    mixer1: 137,
    mixer2: 138,
    feedbackSend: 142,
    feedbackReturn: 143,
    filter1: 131,
    filter2: 132,
    filter3: 164,
    filter4: 165,
    flanger1: 118,
    flanger2: 119,
    formant: 126,
    gateExpander1: 150,
    gateExpander2: 151,
    graphicEQ1: 102,
    graphicEQ2: 103,
    graphicEQ3: 160,
    graphicEQ4: 161,
    parametricEQ1: 104,
    parametricEQ2: 105,
    parametricEQ3: 162,
    parametricEQ4: 163,
    inputNoiseGate: 139,
    output: 140,
    controllers: 141,
    looper: 169,
    phaser1: 122,
    phaser2: 123,
    pitch1: 130,
    pitch2: 153,
    quadChorus1: 156,
    quadChorus2: 157,
    resonator1: 158,
    resonator2: 159,
    reverb1: 110,
    reverb2: 111,
    ringModulator: 152,
    rotarySpeaker1: 120,
    rotarySpeaker2: 121,
    synth1: 144,
    synth2: 145,
    toneMatch: 170,
    tremolo1: 128,
    tremolo2: 129,
    vocoder: 146,
    volumePan1: 127,
    volumePan2: 128,
    volumePan3: 167,
    volumePan4: 168,
    wah1: 124,
    wah2: 125 
}

export const FX_BLOCK_TYPES = [
    'amp',
    'cab',
    'chorus',
    'compressor',
    'multibandCompressor',
    'crossover',
    'delay',
    'multiDelay',
    'drive',
    'enhancer',
    'fxLoop',
    'mixer',
    'feedback',
    'filter',
    'flanger',
    'formant',
    'gateExpander',
    'graphicEQ',
    'parametricEQ',
    'inputNoiseGate',
    'output',
    'controllers',
    'looper',
    'phaser',
    'pitch',
    'quadChorus',
    'resonator',
    'reverb',
    'ringModulator',
    'rotarySpeaker',
    'synth',
    'toneMatch',
    'tremolo',
    'vocoder',
    'volumePan',
    'wah'
]

export const FX_BLOCK_LABELS = {
    amp1: 'Amp 1',
    amp2: 'Amp 2',
    cab1: 'Cab 1',
    cab2: 'Cab 2',
    chorus1: 'Chorus 1',
    chorus2: 'Chorus 2',
    compressor1: 'Compressor 1',
    compressor2: 'Compressor 2',
    multibandCompressor1: 'Multi-band comp 1',
    multibandCompressor2: 'Multi-band comp 2',
    crossover1: 'Crossover 1',
    crossover2: 'Crossover 2',
    delay1: 'Delay 1',
    delay2: 'Delay 2',
    multiDelay1: 'Multi-delay 1',
    multiDelay2: 'Multi-delay 2',
    megatapDelay: 'Mega-tap delay',
    drive1: 'Drive 1',
    drive2: 'Drive 2',
    enhancer: 'Enhancer',
    fxLoop: 'Effects loop',
    mixer1: 'Mixer 1',
    mixer2: 'Mixer 2',
    feedbackSend: 'Feedback send',
    feedbackReturn: 'Feedback return',
    filter1: 'Filter 1',
    filter2: 'Filter 2',
    filter3: 'Filter 3',
    filter4: 'Filter 4',
    flanger1: 'Flanger 1',
    flanger2: 'Flanger 2',
    formant: 'Formant',
    gateExpander1: 'Gate / expander 1',
    gateExpander2: 'Gate / expander 2',
    graphicEQ1: 'Graphic EQ 1',
    graphicEQ2: 'Graphic EQ 2',
    graphicEQ3: 'Graphic EQ 3',
    graphicEQ4: 'Graphic EQ 4',
    parametricEQ1: 'Parametric EQ 1',
    parametricEQ2: 'Parametric EQ 2',
    parametricEQ3: 'Parametric EQ 3',
    parametricEQ4: 'Parametric EQ 4',
    inputNoiseGate: 'Input noise gate',
    output: 'Output',
    controllers: 'Controllers',
    looper: 'Looper',
    phaser1: 'Phaser 1',
    phaser2: 'Phaser 2',
    pitch1: 'Pitch 1',
    pitch2: 'Pitch 2',
    quadChorus1: 'Quad chorus 1',
    quadChorus2: 'Quad chorus 2',
    resonator1: 'Resonator 1',
    resonator2: 'Resonator 2',
    reverb1: 'Reverb 1',
    reverb2: 'Reverb 2',
    ringModulator: 'Ring modulator',
    rotarySpeaker1: 'Rotary speaker 1',
    rotarySpeaker2: 'Rotary speaker 2',
    synth1: 'Synth 1',
    synth2: 'Synth 2',
    toneMatch: 'Tone match',
    tremolo1: 'Tremolo / panner 1',
    tremolo2: 'Tremolo / panner 2',
    vocoder: 'Vocoder',
    volumePan1: 'Volume / pan 1',
    volumePan2: 'Volume / pan 2',
    volumePan3: 'Volume / pan 3',
    volumePan4: 'Volume / pan 4',
    wah1: 'Wah 1',
    wah2: 'Wah 2' 
}

export const FX_PARAMS = {
    amp: [
        { id: 0, label: 'Type', type: PARAM_TYPE.Select, values: FX_PARAM_SELECT_VALUES.ampType },
        { id: 1, label: 'Input drive', type: PARAM_TYPE.Knob },
        { id: 74, label: 'Overdrive', type: PARAM_TYPE.Knob },
        { id: 2, label: 'Bass', type: PARAM_TYPE.Knob },
        { id: 3, label: 'Middle', type: PARAM_TYPE.Knob },
        { id: 4, label: 'Treble', type: PARAM_TYPE.Knob },
        { id: 20, label: 'Presence', type: PARAM_TYPE.Knob },
        { id: 5, label: 'Master volume', type: PARAM_TYPE.Knob },
        { id: 21, label: 'Level', type: PARAM_TYPE.Knob, range: [-80, 20], precision: 1 },
        { id: 22, label: 'Balance', type: PARAM_TYPE.Knob, range: [-100, 100], precision: 1 },
        { id: 16, label: 'Depth', type: PARAM_TYPE.Knob },
        { id: 6, label: 'Preamp low cut', type: PARAM_TYPE.Knob },
        { id: 7, label: 'High cut freq', type: PARAM_TYPE.Knob },
        { id: 8, label: 'Tone freq', type: PARAM_TYPE.Knob },
        { id: 9, label: 'X-former grind', type: PARAM_TYPE.Knob },
        { id: 10, label: 'Bright cap', type: PARAM_TYPE.Knob },
        { id: 12, label: 'X-former low freq', type: PARAM_TYPE.Knob },
        { id: 13, label: 'X-former hi freq', type: PARAM_TYPE.Knob },
        { id: 14, label: 'Tone location', type: PARAM_TYPE.Select },
        { id: 15, label: 'Input select', type: PARAM_TYPE.Select },
        { id: 19, label: 'Supply sag', type: PARAM_TYPE.Knob },
        { id: 23, label: 'Bypass mode', type: PARAM_TYPE.Select },
        { id: 24, label: 'Negative feedback', type: PARAM_TYPE.Knob },
        { id: 25, label: 'Presence freq', type: PARAM_TYPE.Knob },
        { id: 26, label: 'Low res freq', type: PARAM_TYPE.Knob },
        { id: 27, label: 'Low res', type: PARAM_TYPE.Knob },
        { id: 29, label: 'Depth freq', type: PARAM_TYPE.Knob },
        { id: 31, label: 'MV cap', type: PARAM_TYPE.Knob },
        { id: 33, label: 'Harmonics', type: PARAM_TYPE.Knob },
        { id: 34, label: 'Tone stack', type: PARAM_TYPE.Select },
        { id: 35, label: 'B+ time const', type: PARAM_TYPE.Knob },
        { id: 36, label: 'Tube grid bias', type: PARAM_TYPE.Knob },
        { id: 39, label: 'Bright switch', type: PARAM_TYPE.Switch },
        { id: 40, label: 'Boost', type: PARAM_TYPE.Switch },
        { id: 41, label: 'Low res Q', type: PARAM_TYPE.Knob },
        { id: 42, label: 'Preamp bias', type: PARAM_TYPE.Knob },
        { id: 43, label: 'Hi freq', type: PARAM_TYPE.Knob },
        { id: 44, label: 'Hi resonance', type: PARAM_TYPE.Knob },
        { id: 45, label: 'Cut', type: PARAM_TYPE.Switch },
        { id: 46, label: 'X-former drive', type: PARAM_TYPE.Knob },
        { id: 47, label: 'Input trim', type: PARAM_TYPE.Knob },
        { id: 48, label: 'Preamp hardness', type: PARAM_TYPE.Knob },
        { id: 49, label: 'Mv location', type: PARAM_TYPE.Select },
        { id: 50, label: 'Speaker drive', type: PARAM_TYPE.Knob },
        { id: 51, label: 'X-former match', type: PARAM_TYPE.Knob },
        { id: 54, label: 'Sat switch', type: PARAM_TYPE.Select },
        { id: 55, label: 'GraphicEQ band 1', type: PARAM_TYPE.Knob },
        { id: 56, label: 'GraphicEQ band 2', type: PARAM_TYPE.Knob },
        { id: 57, label: 'GraphicEQ band 3', type: PARAM_TYPE.Knob },
        { id: 58, label: 'GraphicEQ band 4', type: PARAM_TYPE.Knob },
        { id: 59, label: 'GraphicEQ band 5', type: PARAM_TYPE.Knob },
        { id: 60, label: 'GraphicEQ band 6', type: PARAM_TYPE.Knob },
        { id: 61, label: 'GraphicEQ band 7', type: PARAM_TYPE.Knob },
        { id: 62, label: 'GraphicEQ band 8', type: PARAM_TYPE.Knob },
        { id: 63, label: 'Bias excursion', type: PARAM_TYPE.Knob },
        { id: 66, label: 'Triode 2 plate freq', type: PARAM_TYPE.Knob },
        { id: 67, label: 'Triode 1 plate freq', type: PARAM_TYPE.Knob },
        { id: 68, label: 'Poweramp tube', type: PARAM_TYPE.Select },
        { id: 69, label: 'Preamp tubes', type: PARAM_TYPE.Select },
        { id: 70, label: 'Out comp clarity', type: PARAM_TYPE.Knob },
        { id: 71, label: 'Character Q', type: PARAM_TYPE.Knob },
        { id: 72, label: 'Character freq', type: PARAM_TYPE.Knob },
        { id: 73, label: 'Character amount', type: PARAM_TYPE.Knob },
        { id: 75, label: 'Out comp amount', type: PARAM_TYPE.Knob },
        { id: 76, label: 'Out comp threshold', type: PARAM_TYPE.Knob },
        { id: 77, label: 'Master trim', type: PARAM_TYPE.Knob },
        { id: 78, label: 'Fat', type: PARAM_TYPE.Switch },
        { id: 79, label: 'Definition', type: PARAM_TYPE.Knob },
        { id: 80, label: 'Preamp CF compress', type: PARAM_TYPE.Knob },
        { id: 81, label: 'Preamp CF time', type: PARAM_TYPE.Knob },
        { id: 84, label: 'Dynamic presence', type: PARAM_TYPE.Knob },
        { id: 85, label: 'Dynamic depth', type: PARAM_TYPE.Knob },
        { id: 86, label: 'Power type', type: PARAM_TYPE.Select },
        { id: 87, label: 'AC line freq', type: PARAM_TYPE.Knob },
        { id: 88, label: 'Poweramp hardness', type: PARAM_TYPE.Knob },
        { id: 91, label: 'Preamp CF ratio', type: PARAM_TYPE.Knob },
        { id: 92, label: 'EQ type', type: PARAM_TYPE.Select },
        { id: 93, label: 'Cathode resist', type: PARAM_TYPE.Knob },
        { id: 96, label: 'Preamp sag', type: PARAM_TYPE.Switch },
        { id: 97, label: 'Bright', type: PARAM_TYPE.Knob },
        { id: 98, label: 'Poweramp bias', type: PARAM_TYPE.Knob },
        { id: 99, label: 'Preamp dynamics', type: PARAM_TYPE.Knob },
        { id: 100, label: 'Hi freq slope', type: PARAM_TYPE.Knob },
        { id: 101, label: 'Variac', type: PARAM_TYPE.Knob },
        { id: 102, label: 'Char type', type: PARAM_TYPE.Select },
        { id: 104, label: 'Presence shift', type: PARAM_TYPE.Switch },
        { id: 105, label: 'Saturation drive', type: PARAM_TYPE.Knob },
        { id: 106, label: 'Crunch', type: PARAM_TYPE.Knob },
        { id: 109, label: 'Out comp type', type: PARAM_TYPE.Select },
        { id: 110, label: 'EQ location', type: PARAM_TYPE.Select },
        { id: 111, label: 'CF comp type', type: PARAM_TYPE.Select },
        { id: 113, label: 'Preamp CF hardness', type: PARAM_TYPE.Knob },
        { id: 114, label: 'PI bias shift', type: PARAM_TYPE.Knob },
        { id: 115, label: 'Motor drive', type: PARAM_TYPE.Knob },
        { id: 116, label: 'Motor time const', type: PARAM_TYPE.Knob },
    ],
    cab: [
        { id: 0, label: 'Cab L', type: PARAM_TYPE.Select },
        { id: 1, label: 'Cab L mic', type: PARAM_TYPE.Select },
        { id: 2, label: 'Cab R', type: PARAM_TYPE.Select },
        { id: 3, label: 'Cab R mic', type: PARAM_TYPE.Select },
        { id: 4, label: 'Link cabs', type: PARAM_TYPE.Switch },
        { id: 5, label: 'Level L', type: PARAM_TYPE.Knob },
        { id: 6, label: 'Level R', type: PARAM_TYPE.Knob },
        { id: 7, label: 'Pan L', type: PARAM_TYPE.Knob, range: [-100, 100], precision: 0 },
        { id: 8, label: 'Pan R', type: PARAM_TYPE.Knob, range: [-100, 100], precision: 0 },
        { id: 9, label: 'Level', type: PARAM_TYPE.Knob, range: [-80, 20] },
        { id: 10, label: 'Balance', type: PARAM_TYPE.Knob, range: [-100, 100], precision: 0 },
        { id: 11, label: 'Link cabs', type: PARAM_TYPE.Select },
        { id: 12, label: 'Link cabs', type: PARAM_TYPE.Select },
        { id: 14, label: 'Link cabs', type: PARAM_TYPE.Knob },
        { id: 15, label: 'Link cabs', type: PARAM_TYPE.Knob },
        { id: 16, label: 'Link cabs', type: PARAM_TYPE.Knob },
        { id: 17, label: 'Link cabs', type: PARAM_TYPE.Knob },
        { id: 18, label: 'Link cabs', type: PARAM_TYPE.Knob },
        { id: 19, label: 'Low cut', type: PARAM_TYPE.Knob },
        { id: 20, label: 'High cut', type: PARAM_TYPE.Knob },
        { id: 21, label: 'Speaker size', type: PARAM_TYPE.Knob },
        { id: 22, label: 'Proximity', type: PARAM_TYPE.Knob },
        { id: 23, label: 'Air', type: PARAM_TYPE.Knob },
        { id: 24, label: 'Motor drive', type: PARAM_TYPE.Knob },
        { id: 25, label: 'Air freq', type: PARAM_TYPE.Knob },
        { id: 26, label: 'Delay L', type: PARAM_TYPE.Knob },
        { id: 27, label: 'Delay R', type: PARAM_TYPE.Knob },
        { id: 28, label: 'Promixity R', type: PARAM_TYPE.Knob },
        { id: 29, label: 'Proximity freq', type: PARAM_TYPE.Knob },
        { id: 30, label: 'Input select', type: PARAM_TYPE.Select },
        { id: 31, label: 'Premap type', type: PARAM_TYPE.Select },
        { id: 32, label: 'Bass', type: PARAM_TYPE.Knob },
        { id: 33, label: 'Middle', type: PARAM_TYPE.Knob },
        { id: 34, label: 'Treble', type: PARAM_TYPE.Knob },
        { id: 35, label: 'Preamp mode', type: PARAM_TYPE.Select },
        { id: 36, label: 'Dephase', type: PARAM_TYPE.Knob },
        { id: 37, label: 'Filter slope', type: PARAM_TYPE.Select },
        { id: 38, label: 'Motor time constant', type: PARAM_TYPE.Knob }
    ]
}

